### ISSUE TITLE
Don't use activeEditor inside provide-function

### ISSUE THREAD

**Issue by jrieken** [belfz/search-crates-io#1]
I came across your blogpost https://medium.com/@marcinbaraniecki/developing-visual-studio-code-extensions-c43a47321296 and as the maintainer of the VS Code I couldn't resit taking a look at your extension code. 

Just FYI - it is best not to use `activeTextEditor` inside `provideXYZ`-calls because it must not always be the active editor for which completions are requested. In your case can do two things

* use the provided `document` and `position` to figure out where you are, or
* at least check that the provided `document` is the document of the active editor. 

Thanks for the nice words ❤️. Happy Coding

**Comment by belfz** [comment]
Thank you @jrieken ! That's an awesome feedback. I will definitely take a look into this.

**Comment by belfz** [comment]
closed with https://github.com/belfz/search-crates-io/commit/6f76130bbf60e498a53238c7cd50529c7d77705e
